name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run Unit Tests
      run: |
        pip install -r requirements.txt  # Install dependencies if needed
        python -m pytest test_app.py     # Run unit tests

  build_image:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Build and push Docker image to Docker Hub
      run: |
        docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/cloud-resume:latest" .
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/cloud-resume:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build_image
    if: ${{ success() }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: jhsd789bnsbnja127mj
        images: "${{ secrets.DOCKERHUB_USERNAME }}/cloud-resume:latest"
        #slot-name: <optional-slot-name>
